server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: LOCATION-SERVICE
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path=/locations/**
        - id: AGENCY-SERVICE
          uri: lb://AGENCY-SERVICE
          predicates:
            - Path=/agencies/**
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**