server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: LOCATION-SERVICE
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path=/locations/**
        - id: AGENCY-SERVICE
          uri: lb://AGENCY-SERVICE
          predicates:
            - Path=/agencies/**
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka