server:
  port: 9296
spring:
  application:
    name: CONFIGURATION
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Andreea-Elena/config
          clone-on-start: true
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka