server:
  port: 9296
spring:
  application:
    name: CONFIGURATION
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Andreea-Elena/config
          clone-on-start: true