server:
  port: 9296
spring:
  application:
    name: CONFIGURATION
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Andreea-Elena/cloud-computing/tree/main/configuration/src/main/resources/application.yml
          clone-on-start: true