server:
  port: 9296
spring:
  application:
    name: CONFIGURATION
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Andreea-Elena/cloud-computing/blob/main/configuration/src/main/resources
            clone-on-start: true